- name: Deploy WAR to Apache Tomcat
  hosts: all
  become: yes
  vars:
    tomcat_version: 11.0.22
    tomcat_user: tomcat
    tomcat_group: tomcat
    tomcat_install_dir: /opt/tomcat
    tomcat_symlink: /opt/tomcat/latest
    tomcat_download_url: "https://dlcdn.apache.org/tomcat/tomcat-11/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    war_download_url: "http://51.20.98.56:8081/repository/dobretech-repo/com/example/myapp/20260604220141/myapp-20260604220141.war"
    war_dest: "{{ tomcat_symlink }}/webapps/myapp.war"

  tasks:
    - name: Install Java
      apt:
        name: openjdk-21-jdk
        state: present
        update_cache: yes

    - name: Create Tomcat group
      group:
        name: "{{ tomcat_group }}"

    - name: Create Tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        shell: /bin/false
        create_home: no

    - name: Create Tomcat installation directory
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Download Tomcat
      get_url:
        url: "{{ tomcat_download_url }}"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        mode: '0644'

    - name: Extract Tomcat
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        creates: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"

    - name: Set permissions
      file:
        path: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        recurse: yes

    - name: Create symlink to Tomcat
      file:
        src: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ tomcat_symlink }}"
        state: link
        force: true

    - name: Ensure webapps directory exists
      file:
        path: "{{ tomcat_symlink }}/webapps"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: '0755'

    - name: Download WAR file from Nexus
      get_url:
        url: "{{ war_download_url }}"
        dest: "{{ war_dest }}"
        url_username: "admin"
        url_password: "Realcalson@123"
        force_basic_auth: yes
        force: yes
        mode: '0644'
        timeout: 30

    - name: Verify WAR file integrity
      shell: "file {{ war_dest }}"
      register: file_check

    - name: Fail if file is not a valid archive
      fail:
        msg: "The WAR file is corrupted!"
      when: "'archive data' not in file_check.stdout"

    - name: Configure Tomcat Manager Users
      blockinfile:
        path: /opt/tomcat/latest/conf/tomcat-users.xml
        marker: ""
        insertbefore: "</tomcat-users>"
        block: |
          <role rolename="manager-gui"/>
          <role rolename="admin-gui"/>
          <user username="admin" password="admin123" roles="manager-gui,admin-gui"/>

    - name: Allow remote access to Manager app
      copy:
        dest: /opt/tomcat/latest/webapps/manager/META-INF/context.xml
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <Context antiResourceLocking="false" privileged="true" >
            <CookieProcessor className="org.apache.tomcat.util.http.Rfc6265CookieProcessor" sameSiteCookies="strict" />
          </Context>

    - name: Allow remote access to Host Manager app
      copy:
        dest: /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <Context antiResourceLocking="false" privileged="true" >
            <CookieProcessor className="org.apache.tomcat.util.http.Rfc6265CookieProcessor" sameSiteCookies="strict" />
          </Context>
      notify: Restart Tomcat

    - name: Enable and start Tomcat service
      systemd:
        name: tomcat
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reexec

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
